### ISSUE TITLE
Images render over other cards

### ISSUE THREAD

**Issue by jeffh0821** [vasqued2/ha-teamtracker-card#53]
Love the integration and the card. Been great having them on my dashboard.

I am having an issue with other cards attempting to paint over the ha-teamtracker-card when they are activated via a click-action. Example is attached.

![image](https://user-images.githubusercontent.com/25091325/236891018-313e35fd-2d63-41e4-be02-b8ae824fdf78.png)

Anyway to get the css to push those images back?

Let me know if additional information is needed.

**Comment by espeir** [comment]
I'm experiencing the same issue.  I don't know when it first started.

![image](https://user-images.githubusercontent.com/65735975/236948600-3a8c8c0e-c5e6-4c24-9f67-a2157c812049.png)

**Comment by mrhelder** [comment]
I'm also having this issue. Not sure when it started. Running 0.7.1 but just updated to 0.7.2
![Screenshot 2023-05-15 132545](https://github.com/vasqued2/ha-teamtracker-card/assets/69739623/4a6379fe-2dc4-447f-a9a7-58b84368b564)

**Comment by vasqued2** [comment]
Thanks.  Just upgraded HA to the May release and noticed it so I think it’s related to that.  Anyone seeing it occurring on an HA release prior to May?

**Comment by vasqued2** [comment]
Confirmed it was related to the May HA release.  Should be fixed in v0.7.3

If it doesn't fix it, try clearing cache and refreshing.  Let me know if there are still issues and on what browser/app/device, etc.

**Comment by c0nt4x** [comment]
I've just updated to the latest version this morning and the overlap is still occurring. I've cleared my cache a few times, reloaded the integration and restarted HA but it still overlaps.
<img width="811" alt="Screenshot 2023-05-16 at 06 38 46" src="https://github.com/vasqued2/ha-teamtracker-card/assets/70321584/2944d923-a601-4684-b1e4-ba632fa34586">

**Comment by c0nt4x** [comment]
I’m using Safari browser. Just checked it in Chrome and it’s fine so it looks like maybe just Safari. I can’t check Firefox because it’s not available on MacBook.

**Comment by espeir** [comment]
Working fine for me after updating on the application (Android) and Chrome browser.

**Comment by jeffh0821** [comment]
Resolved here too. Thanks!

**Comment by c0nt4x** [comment]
Appreciate this issue is closed but, just in case others have the same problem as me, that the latest update didn't fix the overlap, I've just deleted then reaadded the card I had in my dashboard and the overlap no longer exists.

Thanks for the fix @vasqued2

**Comment by vasqued2** [comment]
Looks like the old card was still in your cache until you deleted and re-added.
